spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/mybatis_demo
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver

mybatis:

  mapper-locations: classpath:mybatis/mapper/*/*.xml
  configuration:
    map-underscore-to-camel-case: on


